# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression_owner_id', models.CharField(max_length=30)),
                ('expression_content', models.CharField(max_length=10000)),
                ('expression_link_id', models.CharField(default=None, max_length=30)),
                ('expression_imagefile', models.CharField(default=None, max_length=30)),
                ('broadcast_parent_id', models.CharField(default=None, max_length=30)),
                ('total_upvotes', models.IntegerField(default=0)),
                ('total_downvotes', models.IntegerField(default=0)),
                ('total_broadcasts', models.IntegerField(default=0)),
                ('expression_updated', models.DateTimeField(auto_now_add=True)),
                ('expression_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_url', models.CharField(max_length=150, unique=True)),
                ('link_name', models.CharField(max_length=150)),
                ('link_desc', models.CharField(default=None, max_length=200)),
                ('link_image', models.CharField(default=None, max_length=30)),
                ('link_updated', models.DateTimeField(auto_now_add=True)),
                ('link_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
