# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('express', '0002_auto_20161003_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link_image',
            field=models.CharField(default=None, max_length=60, null=True),
        ),
    ]
