# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('express', '0005_auto_20161005_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion_Expression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discussion_parent_id', models.CharField(max_length=30)),
                ('discussion_expression_owner_id', models.CharField(max_length=30)),
                ('discussion_expression_content', models.CharField(max_length=10000)),
                ('discussion_expression_link_id', models.CharField(default=None, max_length=30, null=True)),
                ('discussion_expression_imagefile', models.CharField(default=None, max_length=30, null=True)),
                ('total_upvotes', models.IntegerField(default=0)),
                ('total_downvotes', models.IntegerField(default=0)),
                ('discussion_expression_updated', models.DateTimeField(auto_now_add=True)),
                ('discussion_expression_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
