# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('express', '0006_discussion_expression'),
    ]

    operations = [
        migrations.AddField(
            model_name='expression',
            name='total_discussions',
            field=models.IntegerField(default=0),
        ),
    ]
