# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0007_expression_total_discussions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expression',
            name='expression_imagefile',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
