# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0008_auto_20161010_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expression',
            name='expression_imagefile',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
