# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0009_auto_20161014_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link_image',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
