# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=150, unique=True)),
                ('url_title', models.CharField(max_length=150)),
                ('url_desc', models.CharField(default=None, max_length=200, null=True)),
                ('url_imagefile', models.CharField(default=None, max_length=100, null=True)),
                ('url_weight', models.DecimalField(decimal_places=10, default=0, max_digits=15)),
                ('url_updated', models.DateTimeField(auto_now_add=True)),
                ('url_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
