# -*- coding: utf-8 -*-

"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 1.10.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

from base import *
import dj_database_url

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*", ]


# Static files (CSS, JavaScript, Images) during deployment
# https://docs.djangoproject.com/en/1.10/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'var/www/static')

# url to access the static files
STATIC_URL = '/static/'

# static files during development wrt base directory
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'templates/include/static'),
)


MEDIA_URL = 'http://s3.ap-south-1.amazonaws.com/the-thing/'

AWS_STORAGE_BUCKET_NAME = 'the-thing'
AWS_ACCESS_KEY_ID = 'AKIAIJV7GGCJGULDTAIA'
AWS_SECRET_ACCESS_KEY = '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'


# place where media files are served wrt base directory
#MEDIA_ROOT = os.path.join('http://the-thing.s3-website.ap-south-1.amazonaws.com', 'media')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

os.environ['DJANGO_SETTINGS_MODULE'] = 'core.settings.heroku'

# For the Postgre
DATABASES = {'default': dj_database_url.config(default=os.getenv('DATABASE_URL'))}

# For the Graph
GRAPHDB_URL = os.environ['GRAPHENEDB_URL']