# -*- coding: utf-8 -*-

"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 1.10.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

from base import *
import dj_database_url

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*", ]

DATABASES = {'default': dj_database_url.config(default=os.getenv('DATABASE_URL'))}

os.environ['DJANGO_SETTINGS_MODULE'] = 'core.settings.heroku'

os.environ['GRAPHDB_URL'] = os.environ['GRAPHENEDB_URL']