# -*- coding: utf-8 -*-

#############
#
# Copyright - Nirlendu Saha
#
# author - nirlendu@gmail.com
#
#############

"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 1.10.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

from base import *
import dj_database_url

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["*", ]


# Static files (CSS, JavaScript, Images) during deployment
# https://docs.djangoproject.com/en/1.10/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'var/www/static')

# url to access the static files
STATIC_URL = '/static/'

# static files during development wrt base directory
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'templates/include/static'),
)

# place where media files are served wrt base directory
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# url to access media files
MEDIA_URL = '/media/'

# from django.conf.global_settings import TEMPLATES
WEBPACK_LOADER = {
    'DEFAULT': {
        'BUNDLE_DIR_NAME': 'bundles/',
        'STATS_FILE': os.path.join(BASE_DIR, 'webpack-stats.json'),
    }
}

REACT = {
    'RENDER': True,
    'RENDER_URL': 'http://127.0.0.1:9009',
}

DATABASES = {'default': dj_database_url.config(default=os.getenv('DATABASE_URL'))}