# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressionPrimary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression_owner_id', models.CharField(max_length=12)),
                ('expression_content', models.CharField(max_length=10000)),
                ('expression_content_url', models.CharField(default=None, max_length=100, null=True)),
                ('expression_imagefile', models.CharField(default=None, max_length=100, null=True)),
                ('expression_weight', models.DecimalField(decimal_places=10, default=0, max_digits=15)),
                ('broadcast_parent_id', models.CharField(default=None, max_length=20, null=True)),
                ('total_upvotes', models.IntegerField(default=0)),
                ('total_broadcasts', models.IntegerField(default=0)),
                ('total_discussions', models.IntegerField(default=0)),
                ('total_collects', models.IntegerField(default=0)),
                ('expression_updated', models.DateTimeField(auto_now_add=True)),
                ('expression_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
