# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlChannelRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=8)),
                ('url_id', models.CharField(max_length=16)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='urlchannelrelation',
            unique_together=set([('channel_id', 'url_id')]),
        ),
    ]
